[package]
name = "imprint"
version = "2.0.6"
description = "Imprint - Intelligent RAW Photo Burst Selection & Aesthetic Sorting App"
authors = ["Luqie"]
edition = "2021"

[lib]
name = "tauri_frontend_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
window-vibrancy = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
debug = false
strip = true
